-- MySQL Script generated by MySQL Workbench
-- Sun Aug 12 00:01:47 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema EvaluacionNutricional
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema EvaluacionNutricional
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `EvaluacionNutricional` DEFAULT CHARACTER SET utf8 ;
USE `EvaluacionNutricional` ;

-- -----------------------------------------------------
-- Table `EvaluacionNutricional`.`Despistaje`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `EvaluacionNutricional`.`Despistaje` (
  `idDespistaje` INT NOT NULL AUTO_INCREMENT,
  `Dni` CHAR(8) NULL,
  `Nombres` VARCHAR(120) NULL,
  `Sexo_id` INT NOT NULL,
  `Edad` INT(3) NULL,
  `Procedencia` VARCHAR(50) NULL,
  `FsVs` VARCHAR(50) NULL,
  `DiagPreHoH` VARCHAR(50) NULL,
  `Peso` DECIMAL(5,2) NULL,
  `Talla` DECIMAL(5,2) NULL,
  `Perimetro` DECIMAL(5,2) NULL,
  `DiagIMC` DECIMAL(5,2) NULL,
  `RiesgoMetabolico` VARCHAR(50) NULL,
  `Responsable` VARCHAR(50) NULL,
  PRIMARY KEY (`idDespistaje`, `Sexo_id`),
  INDEX `fk_DespistajeDeHAyRSM_Sexo2_idx` (`Sexo_id` ASC),
  CONSTRAINT `fk_DespistajeDeHAyRSM_Sexo2`
    FOREIGN KEY (`Sexo_id`)
    REFERENCES `EvaluacionNutricional`.`Sexo` (`idSexo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
