-- MySQL Script generated by MySQL Workbench
-- Sat Aug 11 17:12:00 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema EvaluacionNutricional
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema EvaluacionNutricional
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `EvaluacionNutricional` DEFAULT CHARACTER SET utf8 ;
USE `EvaluacionNutricional` ;

-- -----------------------------------------------------
-- Table `EvaluacionNutricional`.`Sexo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `EvaluacionNutricional`.`Sexo` (
  `idSexo` INT NOT NULL AUTO_INCREMENT,
  `Genero` VARCHAR(45) NULL,
  PRIMARY KEY (`idSexo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `EvaluacionNutricional`.`FichaNutricional`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `EvaluacionNutricional`.`FichaNutricional` (
  `idEvaluacionNutricional` INT NOT NULL AUTO_INCREMENT,
  `Dni` CHAR(8) NULL,
  `Nombres` VARCHAR(45) NULL,
  `Sexo_id` INT NOT NULL,
  `Edad` INT(3) NULL,
  `Peso` DECIMAL(2) NULL,
  `Talla` DECIMAL(2) NULL,
  `PerimetroAbdominal` DECIMAL(2) NULL,
  `DxNutricional` VARCHAR(45) NULL,
  `TratamientoNutricional` VARCHAR(45) NULL,
  `Observaciones` VARCHAR(45) NULL,
  PRIMARY KEY (`idEvaluacionNutricional`, `Sexo_id`),
  INDEX `fk_FichaEvaluacionNutricional_Sexo_idx` (`Sexo_id` ASC),
  CONSTRAINT `fk_FichaEvaluacionNutricional_Sexo`
    FOREIGN KEY (`Sexo_id`)
    REFERENCES `EvaluacionNutricional`.`Sexo` (`idSexo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
